Joss paper
SCIInstitute/UncertainSCI pull request #91
Opened 2021-11-05 19:06 UTC by jessdtate

preparing the repo and paper for a Joss submission

2021-12-30 01:00 UTC, Sumientra requested changes

2022-01-05 01:42 UTC, jessdtate commented on paper/paper.md
> +The probability measure $\mu$ that must be randomly sampled is specially tailored distribution that exploits a concentration of measurable phenomena to provably increase the quality of the candidate
The capitalization of Weighted Approximate Fekete Points is something that @akilnarayan changed, I think.  polynomial chaos emulators was not capitalized.  I'm not sure how much it matters, so perhaps @akilnarayan will weigh in.

2022-01-05 20:26 UTC, Sumientra commented on paper/paper.md
> +The probability measure $\mu$ that must be randomly sampled is specially tailored distribution that exploits a concentration of measurable phenomena to provably increase the quality of the candidate
In general, nouns should never be capitalized, only names. So Fekete yes, points no.

2022-01-05 20:43 UTC, Sumientra commented
Rampersad S, Charlebois C, Tate J, MacLeod R, Brooks DH, Narayan A. Quantification of uncertainty due to tissue conductivity variability in simulations of brain stimulation. IEEE NER, 2021.

2022-01-05 20:47 UTC, Sumientra commented on paper/paper.bib
> +}
@InProceedings{Ram2021,
	title = {Quantification of uncertainty due to tissue conductivity variability in simulations of brain stimulation},
	booktitle = {10th International IEEE EMBS Conference on Neural Engineering},
	author = {Rampersad S, Charlebois C, Tate J, MacLeod R, Brooks DH, Narayan A},
	year = {2021}}

2022-01-12 17:18 UTC, akilnarayan commented on paper/paper.md
> +The probability measure $\mu$ that must be randomly sampled is specially tailored distribution that exploits a concentration of measurable phenomena to provably increase the quality of the candidate
Proper nouns also require capitalization -- so it's the Charles River, not the Charles river even though "river" is a noun. I'd argue that Weighted Approximate Fekete Points is a proper noun since it's a name for something. But indeed I don't think it matters much here, so we'll just un-capitalize most things.

Re: "chaos", I'm never sure whether to capitalize or not. People say things like "polynomial Chaos emulator", or "Polynomial Chaos emulator", or "Polynomial Chaos Emulator". I'm not really sure I want to throw my hat into the ring for any of those, so I vote we just un-capitalize everything (which is how it currently is).

2022-01-12 18:04 UTC, akilnarayan submitted a review, later dismissed

2022-01-12 18:06 UTC, akilnarayan commented on paper/paper.md
> +The probability measure $\mu$ that must be randomly sampled is specially tailored distribution that exploits a concentration of measurable phenomena to provably increase the quality of the candidate
Sorry, I didn't see that these were suggested comments; I thought you had implemented them all. 
Anyway, I should have addressed one of your unimplemented comments in commit d4a4790

2022-01-12 18:30 UTC, akilnarayan submitted a review, later dismissed

2022-01-14 21:07 UTC, jessdtate commented
any one else have any comments before this is merged?  Also I need at least one person to approve to merge.

2022-01-19 22:53 UTC, akilnarayan approved these changes

2022-01-20 22:08 UTC, merged